# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload Python Package

on:
  # 在推送到 master 分支时会自动运行一次
  push:
    branches: 
      - master
  # 可以设定定时任务执行
  schedule:
    # UTC 0 点 30 定期执行一次，跟北京时间大概相距 8 小时，但因为排队可能会稍微延后半小时左右
    # 即北京时间 8 点 30 以后
    - cron: '0 */1 * * *'
    #- cron: '30 0 * * *'

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: 'working'
      run: |
        username: ${{ secrets.USERNAME }}
        pd: ${{ secrets.PASSWORD }}
        SCKEY: ${{ secrets.SCKEY }}
        python 2.py
